### ISSUE TITLE
Unable to save an edited record

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#30]
##### What is the issue? 
I cannot save a previously created record when editing it (after adding a new field into the module)

##### What would you expect to happen?
![image](https://cloud.githubusercontent.com/assets/19467251/15854601/976b80f2-2ca2-11e6-8d00-bed4f94b77e4.png)

##### What steps are needed to replicate the issue?
login to chris
client home page
search for site
pick '10000' 'Blagger end'-----click edit
add a subtype and change any fields
click Save
error message appears

##### What browser does the issue appear on?
Google Chrome

**Comment by Gillardo** [comment]
This is because you have stated that the "Site Contract Number" is a required field.  But it is being hidden automatically because you have said this is your reference field.  
If you are using self generating references, then you do not need to state that the field is required, i have removed this for you, and it now works.
