### ISSUE TITLE
Template area not authorized

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#37]
##### What is the issue? 
When I click on "Templates", I get a message which says "You are not authorized" to perform this action 

![templates2](https://cloud.githubusercontent.com/assets/19469440/15858542/fde88044-2cb8-11e6-987f-72019073d886.JPG)

##### What would you expect to happen?
It not to error!

##### What steps are needed to replicate the issue?
Login > Click "Templates" Tab

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
Works fine for me.  First time i try to load the page the password dialog appears.  Once i login, it is fine and loads for me.  I am going to remove the popup for login, because we are hitting popup blockers all the time, this will be done shortly.  

I will close the issue for the moment, if you can re-replicate it constently, please feel free to re-open the issue
