### ISSUE TITLE
@Calcs not authorized

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#38]
##### What is the issue? 
When I click on "@Calcs", I get a message which says "You are not authorized" to perform this action 

![calcs](https://cloud.githubusercontent.com/assets/19469440/15858628/5c7bfcda-2cb9-11e6-8dea-0b2d9977c546.JPG)

##### What would you expect to happen?
It not to error!

##### What steps are needed to replicate the issue?
Login > Click "@Calcs" Tab

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
I cannot test this functionality as i believe you have changed your password.  Can you either change your password back to admin, send me your password or add me to your database

**Comment by M2iJulieAnne** [comment]
PW is F1r£starter

**Comment by Gillardo** [comment]
Works fine for me.  First time i try to load the page the password dialog appears.  Once i login, it is fine and loads for me.  I am going to remove the popup for login, because we are hitting popup blockers all the time, this will be done shortly.  

I will close the issue for the moment, if you can re-replicate it constently, please feel free to re-open the issue

**Comment by M2iJulieAnne** [comment]
It does it every time on my machine... the message doesn't stay up though, while its loading it just says the message, then it goes.

**Comment by Gillardo** [comment]
please try this again.  i have just logged in with your username and password on the new version and it works fine

**Comment by M2iJulieAnne** [comment]
Yes I can see it now, thanks!
