### ISSUE TITLE
Module - Field not displaying

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#48]
##### What is the issue? 
I have added a field called Company Ref to my company module.  I've logged out then back in.  It doesn't display when I go to the home page as a normal user for some reason;

![company](https://cloud.githubusercontent.com/assets/19469440/16074819/35d9b35c-32e4-11e6-8642-63c56b1e050e.JPG)

##### What would you expect to happen?
Display the field
##### What steps are needed to replicate the issue?
Add details here as steps in order to replicate, for example. 

1. Login
2. Click **Company** (Company Search page!) from top menu
3. Click **Add New**
4. Company Ref field should appear in the "Company" Group

![company2](https://cloud.githubusercontent.com/assets/19469440/16074967/cf2db508-32e4-11e6-8978-7c4365416f39.JPG)

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
You have stated on the module designer that you want Company Ref to be your reference field. Since this field is set as unique and the starting number has been set, thus the system should generate the value, there is no need for it to appear on the add/edit pages.

![image](https://cloud.githubusercontent.com/assets/7406381/16152985/3b02cb2a-349c-11e6-96c6-196cb4336fbd.png)
