### ISSUE TITLE
Templates: Alphabetic ordering on Answer Variable

### ISSUE THREAD

**Issue by M2iJulieAnne** [measure-2-improve/support#67]
##### What is the issue? 
When configuring a measure should the measure type be displaying in alphabetical order?

![field type](https://cloud.githubusercontent.com/assets/19469440/17061236/6fcdfcb8-5025-11e6-87b4-bb8338f4e8a7.png)

##### What would you expect to happen?
Options to be alphabetically ordered

##### What steps are needed to replicate the issue?

1. login
2. Create Template
4. Create Answer Measure
5. Configure variable
6. Select variable "Type" field

##### What browser does the issue appear on?
Chrome

**Comment by Gillardo** [comment]
I dont really think this is that important, i put them in this order because i felt that the number variable type will probably be the most used, so saves the user having to change it.
But since you have mentioned it, i have changed the options in the new version to be in alphabetical order, but if you want them changed because you feel that you use another option more often, let me know

![image](https://cloud.githubusercontent.com/assets/7406381/18430916/6cda9176-78d2-11e6-99e7-a2dbf4da3404.png)

**Comment by M2iJulieAnne** [comment]
Ok, thanks!
