### ISSUE TITLE
Authorisation Dialog

### ISSUE THREAD

**Issue by Don-Gaudoin** [measure-2-improve/support#7]
##### What is the issue? 
need to tidy it up

![image](https://cloud.githubusercontent.com/assets/16575012/15467262/8329dfae-20d5-11e6-981f-c2e1f0b4e7a8.png)

##### What would you expect to happen?
I think it should say the following.

Title = Confirm Authorisation

Wording = Log on to Fusion using the provider nominated?

Options are Green/Red buttons for Yes or No.

**Comment by Gillardo** [comment]
I have had a look at the code, and it is not possible to tell which provider you are using, because in the background a login is actually created for that email address, and it is linked to a provider.

I have however asked, if this screen is even needed at all, if i have created a login and accepted this once, why should i have to do it everytime.

I will update this issue once more information is obtained

**Comment by Don-Gaudoin** [comment]
Getting rid of it entirely would be great.






Regards

Don

Donald Gaudoin | m2i | IT Director
Unit 17, Swallow Court, Devonshire Gate, Tiverton, EX16 7EJ | United Kingdom
Mobile: 07768 483667 | Office: 01884 841884 | Direct: 01934 710215
Email: donald.gaudoin@measure2improve.com<mailto:donald.gaudoin@measure2improve.com> |Web: www.measure2improve.com<http://www.measure2improve.com>

measure2improve is a trading name of Building Software Limited. Registered in England & Wales – Number  3117419

**Comment by Gillardo** [comment]
This has now been removed
